---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: rcrosby256/php-cs-fixer

inputs:
  - name: source-code

run:
  path: ci/scripts/check-code-standards.sh
  dir: source-code
