---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
  - name: source-code
  - name: release

outputs:
  - name: release-artifact

run:
  path: source-code/ci/scripts/extract-release.sh
