---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: prooph/composer
    tag: 7.1

inputs:
  - name: source-code

outputs:
  - name: source-code-with-dependencies

run:
  path: ci/scripts/install-dependencies.sh
  dir: source-code
